get_analog:
  fields:
    join:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box

get_digital:
  fields:
    join:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box

set_analog:
  fields:
    join:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    value_join:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box

set_digital:
  fields:
    join:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    value_join:
      required: true
      selector:
        boolean: {}
